name: benchmarking
on:
  workflow_run:
    workflows: [ "build-and-deploy" ]
    types:
      - completed

jobs:
  execute:
    concurrency: benchmark-execution
    runs-on: lark # FIXME: assign a proper runner for benchmark job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download benchmarking CLI
        uses: actions/download-artifact@v4
        with:
          name: hydradx-bencher
          path: ./bin
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Make binary executable
        run: chmod +x ./bin/hydradx

      - name: Run benchmarks
        id: execute-benchmarks
        run: ./scripts/benchmarking.sh --all --bin ./bin/hydradx 2>&1 | tee benchmark_results.log

      - name: Upload benchmarking results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark_results.log
          retention-days: 3  # Optional: Keeps artifacts for 3 days

      - name: Upload weights directory
        id: bencher-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-weights
          path: weights/
          retention-days: 3  # Optional: Keeps artifacts for 3 days

      - name: Get PR number from workflow_run event
        id: get-pr-number
        run: echo "PR_NUMBER=$(jq -r '.pull_requests[0].number' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Sticky Pull Request Comment
        #if: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
        uses: marocchino/sticky-pull-request-comment@v2.1.0
        with:
          number: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
          message: |
            Benchmarks at commit ${{ github.event.workflow_run.head_sha }} have been executed successfully.
            [View results](${{ steps.bencher-artifacts.outputs.artifact-url }})